# Generated by Django 4.0.2 on 2022-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_link_options_alter_link_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='monitored',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
