# Generated by Django 4.0.2 on 2022-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_link_current_price_alter_link_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-date_created', '-date_updated']},
        ),
        migrations.AlterField(
            model_name='link',
            name='date_created',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='date_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
