# Generated by Django 4.0.2 on 2022-06-02 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_link_options_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.FileField(null=True, upload_to='product-thumbnails', validators=[django.core.validators.validate_image_file_extension], verbose_name='photo'),
        ),
    ]
